language: node_js
sudo: false
dist: trusty
install:
  - npm install
cache:
  directories:
    - node_modules
addons:
  chrome: stable
# http://www.jackpu.com/jie-jue-karma-zai-travis-zhao-bu-dao-chrome_binde-wen-ti/
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test
  - npm run build:exam
branches:
  only:
  - master
node_js:
  - '8'
env:
 global:
   - GH_REF: github.com/JesseZhao1990/JesseZhao1990.github.io.git
