language: node_js
sudo: false
dist: trusty
install:
  - npm install
cache:
  directories:
    - node_modules
addons:
  chrome: stable
# http://www.jackpu.com/jie-jue-karma-zai-travis-zhao-bu-dao-chrome_binde-wen-ti/
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run build
after_script:
  - git clone https://github.com/jinzhou2017/jinzhou2017.github.io.git
  - rm -rf ./jinzhou2017.github.io/*
  - cp -rf ./dist/* ./jinzhou2017.github.io
  - cd ./jinzhou2017.github.io
  _ git init
  - git config user.name "jinzhou2017"
  - git config user.email "952973039@qq.com"
  - git add .
  - git commit -m 'update'
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:maste

branches:
  only:
  - master
node_js:
  - '8'
env:
 global:
   - GH_REF: github.com/jinzhou2017/jinzhou2017.github.io.git
