language: node_js
sudo: false
dist: trusty
install:
  - npm install
cache:
  directories:
    - node_modules
addons:
  chrome: stable
# http://www.jackpu.com/jie-jue-karma-zai-travis-zhao-bu-dao-chrome_binde-wen-ti/
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run build
after _success:
  - git clone https://github.com/jinzhou2017/jinzhou2017.github.io.git
  - cd ./jinzhou2017.github.io
  - git config --global user.name jinzhou2017
  - git config --global user.email jinzhou223@163.com
  - rm -rf /home/you-app/jinzhou2017.github.io/*
  - cp /home/you-app/dist/* /home/you-app/jinzhou2017.github.io
  - git add .
  - git commit -m 'update'
  - git push -u origin master

branches:
  only:
  - master
node_js:
  - '8'
env:
 global:
   - GH_REF: github.com/JesseZhao1990/JesseZhao1990.github.io.git
